import "./globals.css";
import Navbar from "./components/Navbar"; 
import Footer from "./components/Footer"; 
import BottomNav from "./components/BottomNav";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "MxPo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased font-mono">
        <Navbar />      
        {children}
        
        <div className="hidden md:block">
          <Footer />
        </div>
        
        <div className="block md:hidden">
          <BottomNav />
        </div>
        
        <Toaster
          position="bottom-right"
          toastOptions={{
            duration: 3000,
            style: { fontSize: "14px", padding: "12px 16px" },
          }}
        />  
      </body>
    </html>
  );
}
